version: "2"

services:
  database:
    image: postgres:10.13-alpine
    environment:
      POSTGRES_PASSWORD: "Postgres2019!"
      APP_DB_NAME: conexa-saude
    ports:
      - "15432:5432"
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres-compose-network

  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    links:
      - database
    networks:
      - postgres-compose-network

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    depends_on:
      - backend
    ports:
      - 7070:80
    links:
      - backend
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
